apiVersion: v1
kind: Pod
metadata:
  name: custom
  labels:
    app: custom
# deprecated since kubernetes v1.30
#  annotations:
#    container.apparmor.security.beta.kubernetes.io/shell: 'apparmor-deny-test'

spec:
  containers:
  - name: custom
    image: alpine:latest
    command: ["/bin/sh"]
    args:
    - "-c"
    - "sleep 99999999"
    securityContext:
# new since kubernetes v1.30
      appArmorProfile:
        type: Localhost
        localhostProfile: apparmor-deny-test
