apiVersion: v1
kind: Pod
metadata:
  name: default
  labels:
    app: default
spec:
  containers:
    - name: default
      image: alpine:latest
      command: ["/bin/sh"]
      args:
        - "-c"
        - "sleep 99999999"
