apiVersion: v1
kind: Pod
metadata:
  name: restricted
  labels:
    app: restricted
# deprecated since kubernetes v1.30
#  annotations:
#    container.apparmor.security.beta.kubernetes.io/restricted: 'runtime/default'

spec:
  containers:
  - name: restricted
    image: alpine:latest
    command: ["/bin/sh"]
    args:
    - "-c"
    - "sleep 99999999"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
# new since kubernetes v1.30
      appArmorProfile:
        type: RuntimeDefault
