apiVersion: v1
kind: Pod
metadata:
  name: shell-unconfined
  labels:
    app: shell-unconfined
spec:
  containers:
    - name: shell
      image: alpine:latest
      command: ["/bin/sh"]
      args:
        - "-c"
        - "sleep 99999999"
      securityContext:
        appArmorProfile:
          type: "Unconfined"
