apiVersion: v1
kind: Pod
metadata:
  name: unconfined
  labels:
    app: unconfined
spec:
  containers:
    - name: unconfined
      image: alpine:latest
      command: ["/bin/sh"]
      args:
        - "-c"
        - "sleep 99999999"
      securityContext:
        appArmorProfile:
          type: "Unconfined"
