---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  selector:
    matchLabels:
      app: keycloak-app
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      containers:
        - name: keycloak-container
          image: jboss/keycloak:6.0.1
          volumeMounts:
            - name: keycloak-persistent-data
              mountPath: /opt/jboss/keycloak/standalone/data
          env:
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "password"
      volumes:
      - name: keycloak-persistent-data
        persistentVolumeClaim:
          claimName: keycloak-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "keycloak.local"
spec:
  selector:
    app: keycloak-app
  ports:
  - port: 8080
  type: LoadBalancer
