gateways:
  istio-ingressgateway:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      name: http2
      nodePort: 80
    - port: 443
      name: https
      nodePort: 443
    - port: 31400
      name: tcp
      nodePort: 31400
    - port: 15011
      targetPort: 15011
      name: tcp-pilot-grpc-tls
    - port: 8060
      targetPort: 8060
      name: tcp-citadel-grpc-tls
    - port: 853
      targetPort: 853
      name: tcp-dns-tls
    - port: 15030
      targetPort: 15030
      name: http2-prometheus
    - port: 15031
      targetPort: 15031
      name: http2-grafana
    - port: 2222
      targetPort: 2222
      name: ssh

# Istio mutual TLS is disabled for dataplane by default,
# we keep that default in order to demonstrate meshpolicies.
#global:
#  mtls:
#    enabled: true
