kind: ServiceAccount
apiVersion: v1
metadata:
  name: bound-service-account
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: unbound-service-account
---
apiVersion: v1
kind: Pod
metadata:
  name: run-as-non-root
  labels:
    app: run-as-non-root
spec:
  containers:
    - name: run-as-non-root
      image: quay.io/tsaarni/capabilities-test:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Pod
metadata:
  name: run-as-root
  labels:
    app: run-as-root
spec:
  containers:
    - name: run-as-root
      image: quay.io/tsaarni/capabilities-test:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: run-as-root-drop-all-caps
  labels:
    app: run-as-root-drop-all-caps
spec:
  containers:
    - name: run-as-root-drop-all-caps
      image: quay.io/tsaarni/capabilities-test:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
        capabilities:
          drop:
            - all
---
apiVersion: v1
kind: Pod
metadata:
  name: run-as-root-drop-all-caps-escalation-true
  labels:
    app: run-as-root-drop-all-caps-escalation-true
spec:
  containers:
    - name: run-as-root-drop-all-caps
      image: quay.io/tsaarni/capabilities-test:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: true
        capabilities:
          drop:
            - all
---
apiVersion: v1
kind: Pod
metadata:
  name: run-as-root-drop-all-caps-add-bind
  labels:
    app: run-as-root-drop-all-caps-add-bind
spec:
  containers:
    - name: root-drop-all-caps-add-bind
      image: quay.io/tsaarni/capabilities-test:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
        capabilities:
          drop:
            - all
          add:
            - NET_BIND_SERVICE
---
apiVersion: v1
kind: Pod
metadata:
  name: non-root-drop-all-caps
  labels:
    app: non-root-drop-all-caps
spec:
  containers:
    - name: non-root-drop-all-caps
      image: quay.io/tsaarni/capabilities-test:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000 # remove when running with restricted scc on openshift
        capabilities:
          drop:
            - all
---
apiVersion: v1
kind: Pod
metadata:
  name: non-root-drop-all-caps-add-bind
  labels:
    app: non-root-drop-all-caps-add-bind
spec:
  containers:
    - name: non-root-drop-all-caps-add-bind
      image: quay.io/tsaarni/capabilities-test:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000 # remove when running with restricted scc on openshift
        capabilities:
          drop:
            - all
          add:
            - NET_BIND_SERVICE
---
apiVersion: v1
kind: Pod
metadata:
  name: non-root-privilege-escalation-false
  labels:
    app: non-root-privilege-escalation-false
spec:
  containers:
    - name: non-root-privilege-escalation-false
      image: quay.io/tsaarni/capabilities-test:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000 # remove when running with restricted scc on openshift
---
apiVersion: v1
kind: Pod
metadata:
  name: non-root-drop-all-caps-privilege-escalation-true
  labels:
    app: non-root-drop-all-caps-privilege-escalation-true
spec:
  containers:
    - name: non-root-privilege-escalation-false
      image: quay.io/tsaarni/capabilities-test:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: true
        runAsNonRoot: true
        runAsUser: 1000 # remove when running with restricted scc on openshift
        capabilities:
          drop:
            - all
---
apiVersion: v1
kind: Pod
metadata:
  name: root-add-caps
  labels:
    app: root-add-caps
spec:
  containers:
    - name: root-add-caps
      image: quay.io/tsaarni/capabilities-test:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        capabilities:
          add:
            - NET_RAW
            - NET_ADMIN
---
apiVersion: v1
kind: Pod
metadata:
  name: non-root-add-caps
  labels:
    app: non-root-add-caps
spec:
  containers:
    - name: non-root-add-caps
      image: quay.io/tsaarni/capabilities-test:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 1000 # remove when running with restricted scc on openshift
        capabilities:
          add:
            - NET_RAW
            - NET_ADMIN
