apiVersion: v1
kind: Pod
metadata:
  name: shell-nonroot
  labels:
    app: shell-nonroot
spec:
  containers:
    - name: shell-nonroot
      image: myalpine:latest
      imagePullPolicy: Never
      command: ["/bin/sh"]
      args:
        - "-c"
        - "while true; do inotifywait --event move /secret; cat /secret/password; ls -laR /secret; done"
      volumeMounts:
        - mountPath: /secret
          name: mysecret
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - all
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true

  securityContext:
    fsGroup: 10000
    # runAsUser: 1234
    # runAsGroup: 5678

  volumes:
  - name: mysecret
    secret:
      secretName: mysecret
      defaultMode: 0440
      optional: true
