apiVersion: v1
kind: Pod
metadata:
  name: shell
  labels:
    app: shell
spec:
  containers:
    - name: shell
      image: alpine:latest
      command: ["/bin/sh"]
      args:
        - "-c"
        - "sleep 99999999"
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /secret
          name: mysecret
#  securityContext:
#    fsGroup: 1000660000

  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-pvc
  - name: mysecret
    secret:
      secretName: mysecret
